services:
  app:
    image: php:8.2-fpm
    volumes:
      - ./src/src:/var/www/html

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

